### ISSUE TITLE
config.json.example

### ISSUE THREAD

**Issue by moafred** [Rikj000/MoniGoMani#2]
Hello there !

`config.json` is a user parameter file, i suggest to create an `config.json.example` and let the user modify it.

**Comment by Rikj000** [comment]
You are right that it contains sensitive personal information, but I'll always release those fields blank & instruct our users delete this info when sharing!   

The problem however is that altering things in the `config.json` can heavily impact the results that will be made.
Due to that I see `config.json` & `MoniGoManiHyperOpted` being tied to each other and both should be part of a release, with the `config.json` also acting as an example too.

We are however planning to someday start releasing individual `BTC_config.json` & `USDT_config.json` files, as well as individual `BTC_MoniGoManiHyperOpted.py` & `USDT_MoniGoManiHyperOpted.py` releases.

This issue could be resolved if Freqtrade where to split the config.json into a `personal_info.json` & `config.json` which would make sharing less dangerous.

**Comment by moafred** [comment]
Thanks for the reply, you're right, the good solution is to extract the sensitive data elsewhere.
I'm closing this issue :)
