### ISSUE TITLE
❓ Can you export MoniGoMani settings to a remote `"vanilla" (Docker)` Freqtrade instance?

### ISSUE THREAD

**Issue by dystopy** [Rikj000/MoniGoMani#202]
Hey !

First of all, many thanks for this project, it's really helful to optimize my strategies.

Currently, I have 2 instances of Freqtrade : 1 on  Rasp. Pi4 arch, which is my "production" instance, based on "vanilla" last version of  freqtrade.
As you may know, Pi4 would be quite limited if I wanted to hyperopt, so that's why I have a "on the go" instance of MoniGoMani/Freqtrade on an AMD64, just in order to hyperopt & backtest.

Here my question : is it possible to export all hyperopted values & settings from my MoniGoMani instance to my "vanilla" Freqtrade instance ?

I saw the issue https://github.com/Rikj000/MoniGoMani/issues/197, it's quite clear I just have to copy/paste 5 configurations files, but I'm not sure if it's compatible with a vanilla freqtrade instance.

Thanks !

**Comment by Rikj000** [comment]
> Here my question : is it possible to export all hyperopted values & settings from my MoniGoMani instance to my "vanilla" Freqtrade instance ?
> 

This currently isn't possible with `docker` because it will always install the latest version of Freqtrade which currently isn't supported by MGM *(See issue; https://github.com/Rikj000/MoniGoMani/issues/91#issuecomment-879241169)*

However you can do the following:
- Do a clean [`source` install of MGM](https://monigomani.readthedocs.io/Docs-VeryQuickStart/) on your main machine & RPi *(Easiest/Recommended)*
- Do a clean [`source` install of MGM](https://monigomani.readthedocs.io/Docs-VeryQuickStart/) on your main machine & a clean `source` install of Freqtrade on your RPi **on the exact same commit** as the Freqtrade used by MGM on your main machine + make sure to also install the dependency package versions used in that specific commit.

Then HyperOpt/Backtest on your main machine.
Once done copy over the changed [config files](https://monigomani.readthedocs.io/Docs-MoniGoMani/#how-to-configure-monigomani) to your RPi & dry/live run on there.

But indeed, `docker` is not supported at this point in time, not with MGM & not with vanilla Freqtrade + MGM.
