### ISSUE TITLE
Better core `trend` indicator for trend detection

### ISSUE THREAD

**Issue by denvers** [Rikj000/MoniGoMani#39]
MGM sometimes opens a trade at a peek right before a crash
Trend detection should prevent MGM to open a trade at a peek right before it crashes.

Probably caused by a detection delay.

**Comment by rvasilev** [comment]
Indeed, trend detection is "a little bit off". A lot of "to late" buy signals, looks like because of lagging `plud_di` `minus_di`.

https://user-images.githubusercontent.com/95467/123705310-76bd0280-d86f-11eb-8563-8facc48d2e9d.mp4


https://user-images.githubusercontent.com/95467/123705350-82a8c480-d86f-11eb-8220-ce72da5f922d.mp4
