### ISSUE TITLE
Add ability to change mgm-config-hyperopt.json file name from main config / cli

### ISSUE THREAD

**Issue by rvasilev** [Rikj000/MoniGoMani#65]
This will make hyperopted parameters easy interchangable without need to edit strategy file.

```sh
freqtrade backtesting -s MoniGoManiHyperStrategy -c ./user_data/mgm-config.json -c ./user_data/mgm-config-private.json -c CUSTOM_CONFIG_MGM_HYPEROPT_FOR_TESTING
```
https://github.com/Rikj000/MoniGoMani/blob/07d5e8074b7a5e91756da3edf409a80e907294b0/user_data/strategies/MasterMoniGoManiHyperStrategy.py#L60

**Comment by Rikj000** [comment]
That would have been nice but it's sadly not possible. 

MoniGoMani uses it's own custom json loading because we need those the parameters in those files during the initialization of the classes. 
And Freqtrades dp (Data Provider), where these config files provided in the commands are available, is not yet available at that point in the code. Only after the strategy has initialized we can use them like that.

**Comment by rvasilev** [comment]
@Rikj000 could you reconsider loading logic at least?

Say, when there's existent `mgm-config-hyperopt.tmp.json` - load it in the place of `mgm-config-hyperopt.json`

**Comment by Rikj000** [comment]
> @Rikj000 could you reconsider loading logic at least?
> 
> Say, when there's existent `mgm-config-hyperopt.tmp.json` - load it in the place of `mgm-config-hyperopt.json`

I did yesterday and decided to not change it?
Really don't see what the benefit of this would be.
Just (copy &) rename your `mgm-config-hyperopt.json` first before extracting/applying new HOs by command if you'd like to keep a backup of it.
