### ISSUE TITLE
Rename to `.example.json` config files and `.gitignore` original files

### ISSUE THREAD

**Issue by rvasilev** [Rikj000/MoniGoMani#74]
So `mgm-config` could be left alone with best recommended _vanilla / unchanged_ settings and most of the tuning will be done via `mgm-config-private`.

https://github.com/Rikj000/MoniGoMani/blob/9064a37eb73d601bb64b6cb867ff4d9f7249aa5c/user_data/strategies/MasterMoniGoManiHyperStrategy.py#L56-L83

Most probably the logical and almost drop-in replacement way to implement is [freqtrade.configuration.Configuration](https://github.com/freqtrade/freqtrade/blob/dce01b054228ae657df96c00300e17b770908911/freqtrade/configuration/configuration.py).from_files() .

```py
class Configuration:
    """
    Class to read and init the bot configuration
    Reuse this class for the bot, backtesting, hyperopt and every script that required configuration
    """
```

**Comment by Rikj000** [comment]
Sorry man but absolutely not! `mgm-config-private.json` should contain no settings related to configuration!
This file is only meant for delicate private information, such as usernames, passwords, keys, domain names, tokens and such.
All actual settings belong in `mgm-config.json` and if you need the latest official again then you can just grab it from GitHub or through git :slightly_smiling_face: 

We do this to keep `mgm-config.json` setups easy to share and to reduce the risk of someone leaking out his private information!
If you would accidentally post your current `mgm-config-private.json` then that would be very bad for you, since then with access to the file, can use it to access your Exchange API / wallet!

Also I don't see what's wrong with MGM's current config loading? It's not long? The setting of the class parameters after the json loading is rather lengthy though. There I think we could perhaps improve, but we would need to be very carefully that everything keeps initializing as expected.

FYI: I tried Freqtrades config accessing through the `dataprovider` but that doesn't work since we already need it while `MasterMoniGoManiHyperStrategy` is initializing and by then the `dataprovider` is not yet available.

**Comment by rvasilev** [comment]
I see your point, but there's no way it can reduce the risk of leaking.

`mgm-config-private.json` should be out of git tree and placed in `.gitignore` by default if we're concerned about the leakage of sensitive data. Otherwize - pushing once to github will turn the catastrophe.

Obviously there should be `mgm-config-private.json.example` in tree.

---
Nothing is wrong with current config loading except that config should be overridable by freqtrade design. You can declare config in the `strategy.py` and override it in `config.json`. And after that - override more in `config-1.json`, `config-2.json` etc.

The main reason to override - there'll be no need to manually merge local changes and upstream changes to `mgm-config` after `git pull`. All locally tuned parameters could be stored in out of tree `mgm-config-private`.

**Comment by Rikj000** [comment]
> Obviously there should be `mgm-config-private.json.example` in tree.

The one provided is an example, on my end I got that fixed up with Linux system links, but sure we can rename to `.example` and `.gitignore` + update the installation guide for it to protect contributing developers more.

> The main reason to override - there'll be no need to manually merge local changes and upstream changes to `mgm-config` after `git pull`. All locally tuned parameters could be stored in out of tree `mgm-config-private`.

Same goes for this, we'll rename to `.example` and `.gitignore` + update the installation guide for it to improve upon the ease of git pulling.

I'll add following copy/paste command in the docs to make this really easy to do too:
```powershell
cp ./user_data/mgm-config.example.json ./user_data/mgm-config.json && cp ./user_data/mgm-config-private.example.json ./user_data/mgm-config-private.json
```

**Comment by rvasilev** [comment]
OK. `private` parts will be protected from the accidental git-pushing.

If there's no other special reason to not merge `mgm-config` and `mgm-config-private` during strategy initialization and hyperopting, I'll PR in some time.

```json
"exchange": ["name", "key", "secret"], "apiserver", "telegram"
```
will be popped out from config to not accidentally show on screenshots/hyperopt/backtest stdouts

**Comment by Rikj000** [comment]
> If there's no other special reason to not merge `mgm-config` and `mgm-config-private` during strategy initialization and hyperopting, I'll PR in some time.

The `fiat_display_currency` I also have in the private section, since that way you don't have to share your local currency which gives away a part of where you are located when you share your `mgm-config.json`.

Same goes to `bot_name`, if people configure that, then it only personalizes the config file but changes nothing to the strategy, thus it makes shared files more cluttered and personalized.

But if you want feel free to PR the changes we discussed here! :slightly_smiling_face:
